### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by snirOhayon** [Apollon77/node-mbus#44]
when i try to **npm** install i get error:
"MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual St
udio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Develop\Converters\z-Protoccol-Test\m-bus-client\node_modu
les\node-mbus\build\binding.sln]".

i try to install windows-build-tools still dont work

**Comment by Apollon77** [comment]
This npm package has native code that needs to be compiled on install. You need to get a working "microsoft build environment" on the machine where you want to install it.
When https://www.npmjs.com/package/windows-build-tools is not working then it is very strange because this should bring all tools.

Then sorry but I can not really help here ...

Try:
To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual St
udio 2005 or 3) add the location of the component to the system path if it is installed elsewhere. [C:\Develop\Converters\z-Protoccol-Test\m-bus-client\node_modu
les\node-mbus\build\binding.sln]".
